#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf % "
backend web-backend
	balance roundrobin
	option fowardfor
	server 9318-web-01 54.175.18.109 check
	server 9318-web-02 35.174.205.159 check
frontend proxynode
	bind *:80
	mode http
	default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
