#!/usr/bin/env bash
# fixing what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
apt-get update -y
apt-get -y install nginx
sed -i 's/listen 80 default_server;/listen 80 default_server;\n    listen [::]:80 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
