#!/usr/bin/env bash
#SSH client configuration file

# Host *
# SendEnv LANG LC_*
# HashKnownHosts yes
# GSSAPIAuthentication yes
# GSSAPIDelegateCredentials no
# IdentityFile ~/.ssh/school
# PasswordAuthentication no

OR
Host 100.24.238.171
IdentityFile ~/.ssh/school
PasswordAuthentication no
